### PR TITLE
Fixes Issue #15: Removes "do_cloudflare" checks. No credentials for /ips endpoint.

### LINKED ISSUE #15: Fatal errors when upgrading due to null on Cloudflare::$api property.
When first upgrading, getting the following fatal error:

```
Fatal error: Uncaught Error: Call to a member function set_api_credentials() on null in /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-content/plugins/wp-rocket/inc/Addons/Cloudflare/Cloudflare.php:567 
Stack trace: #0 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-content/plugins/wp-rocket/inc/Addons/Cloudflare/Subscriber.php(263): WPMedia\Cloudflare\Cloudflare->get_cloudflare_ips() 
#1 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-includes/class-wp-hook.php(286): WPMedia\Cloudflare\Subscriber->set_real_ip('') 
#2 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#3 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) 
#4 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-settings.php(525): do_action('init') 
#5 /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-config.php(106): require_once('/home/boniasty/...') 
#6 /ho in /home/boniasty/domains/buldogangielski-klub.pl/public_html/wp-content/plugins/wp-rocket/inc/Addons/Cloudflare/Cloudflare.php on line 567
```
Why?

1. WordPress fires the '`init`' event.
2. The `Subscriber::set_real_ip()` method is called.
3. There's not check to determine if `'do_cloudflare'` is on or off. <- Problem!
4. It calls `Cloudflare->get_cloudflare_ips()`.
5. But wait a minute, if `'do_cloudflare'` is off, then the `Cloudflare::$api` property was never set.
6. So when `Cloudflare->get_cloudflare_ips()` runs, `$api` is `null` and throws the fatal error.

Root cause:
Don't let the Subscriber call `Cloudflare` methods that require the `APIClient`. How? Check if `'do_cloudflare'` is on first. If no, bail out.

### PR DESCRIPTION
**Pull request by hellofromtonya**
Per our discussion here https://github.com/wp-media/cloudflare/issues/15#issuecomment-588290706, this PR does the following:

1. Closes #15 
2. Removes `do_cloudflare` checks and code.
3. Makes `/ips` endpoint not need API credentials.

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@crystinutzaa Notice that this PR removes the `"do_cloudflare"` checks everywhere, including in the update settings method. That means it won't delete the transient when switching from enable to disable. Instead, it retains the last settings in the db, if any.

Why?

The intent in Rocket is _not load_ this Addon when `"do_cloudflare"` is not enabled. Therefore, this code won't run anyway.

- What problems do you foresee? 
- Do we need to delete the transient when going from enable to disable and disable to enable? 
- If yes, then I'm thinking we should it in Rocket and not here. What do you think?

**Comment by crystinutzaa** [comment]
If the checks are done in WP Rocket and not in this package, then I don't see any issues with this change.
I assume the access to this package will be restricted by `do_cloudflare` option (On / Off), right?

However, deleting the transient when Cloudflare addons is enabled / disabled is required to revalidate the credentials. This can be done in WP Rocket plugin and not in this package.

**Comment by hellofromtonya** [comment]
>I assume the access to this package will be restricted by `do_cloudflare` option (On / Off), right?

@crystinutzaa Yes.

>However, deleting the transient when Cloudflare addons is enabled / disabled is required to revalidate the credentials. This can be done in WP Rocket plugin and not in this package.

👍 We'll add that into the Rocket Addon handler. Thanks @crystinutzaa

File: Subscriber.php [hunk 1]
```diff
@@ -166,7 +158,7 @@ public function auto_purge() {
 		}
 
 		// Purge CloudFlare.
-		$cf_purge = $this->cloudflare->purge_cloudflare();
+		$this->cloudflare->purge_cloudflare();
```
Comment (hellofromtonya) [inline Subscriber.php]: Removes the variable assignment, as the variable is not used.

File: Subscriber.php [hunk 2]
```diff
@@ -499,10 +477,9 @@ public function save_cloudflare_options( $old_value, $value ) {
 			}
 		}
 
-		if ( (bool) $cloudflare_update_result ) {
+		if ( [] !== $cloudflare_update_result ) {
```
Comment (hellofromtonya) [inline Subscriber.php]: The variable is an array data type. Here we can check that it's not equal to an empty array. It's a wee bit faster as it doesn't have to do a type cast to boolean.

File: Tests/Integration/APIClient/getIps.php [hunk 3]
```diff
@@ -2,24 +2,23 @@
...
 class Test_GetIps extends TestCase {
 
-	public function testShouldThrowErrorWhenInvalidCredentials() {
+	public function testShouldReturnIpsWhenNoCredentials() {
 		self::$api->set_api_credentials( null, null, null );
 
-		$this->expectException( AuthenticationException::class );
-		$this->expectExceptionMessage( 'Authentication information must be provided' );
-		self::$api->get_ips();
+		$response = self::$api->get_ips();
```
Comment (hellofromtonya) [inline Tests/Integration/APIClient/getIps.php]: No more error thrown here. It will get the CF IPs without credentials.

File: Tests/Integration/Cloudflare/getCloudflareIps.php [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+use Brain\Monkey\Functions;
+use WPMedia\Cloudflare\Cloudflare;
+
+/**
+ * @covers WPMedia\Cloudflare\Cloudflare::get_cloudflare_ips
+ * @group  Cloudflare
+ * @group  CloudflareManager
+ */
+class Test_GetCloudflareIps extends TestCase {
```
Comment (hellofromtonya) [inline Tests/Integration/Cloudflare/getCloudflareIps.php]: Whoops, we have the name of this test case wrong.

File: Tests/Unit/Cloudflare/getCloudflareIps.php [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+use Brain\Monkey\Functions;
+use Mockery;
+use WPMedia\Cloudflare\Cloudflare;
+
+/**
+ * @covers WPMedia\Cloudflare\Cloudflare::get_cloudflare_ips
+ * @group  Cloudflare
+ * @group  CloudflareManager
+ */
+class Test_GetCloudflareIps extends TestCase {
```
Comment (hellofromtonya) [inline Tests/Unit/Cloudflare/getCloudflareIps.php]: Whoops, we had the name of this test case wrong. This PR fixes it.

File: Subscriber.php [hunk 6]
```diff
@@ -122,10 +122,6 @@ public function set_varnish_purge_request_host( $host ) {
 	 * @return bool
 	 */
 	private function should_filter_varnish() {
```
Comment (Tabrisrp) [inline Subscriber.php]: Doesn't this whole method feels weird now in this package? It's very specific to Rocket

Comment (hellofromtonya) [reply Subscriber.php]: You're right @Tabrisrp. It is weird here. 

There are other tightly coupled instance of Rocket in this package too that need a redesign.

Let's circle back to this at a later date as we work on our Addons and package separation.

Comment (hellofromtonya) [reply Subscriber.php]: @Tabrisrp The more I think about this, we need these methods as part of the Varnish addon and not the Cloudflare addon. Why? If Cloudflare is not enabled, these files will not load in Rocket. But what if Varnish is turned on? What do you think?
